### ISSUE TITLE
请问spos[pos1] = spos[pos2] = 2的作用是啥

### ISSUE THREAD

**Issue by VectorChanger0** [SeoSangwoo/Attention-Based-BiLSTM-relation-extraction#6]
`       spos = np.zeros(MAX_SENTENCE_LENGTH)#一个向量`
`        spos[pos1] = spos[pos2] = 2； pos.append(spos)`

这个pos在Attention里用到，却只是
`if vu.shape == pos.shape:
        vu = tf.add(vu, pos)`
之后却没有使用，这个对应论文里面的哪一点，哪一个变量呢

**Comment by roomylee** [comment]
please in english.
